import { Config, Context, Effect, Layer, Schema } from "effect";

import { GeometrySidecar, NetworkSnapshot } from "../domain/transit/index.js";

export const ArtifactManifest = Schema.Struct({
  schemaVersion: Schema.Literal("1"),
  version: Schema.String.check(Schema.isNonEmpty()),
  snapshotUrl: Schema.String.check(Schema.isNonEmpty()),
  geometryUrl: Schema.String.check(Schema.isNonEmpty()),
  routeMapUrl: Schema.optionalKey(Schema.String.check(Schema.isNonEmpty())),
});
export interface ArtifactManifest extends Schema.Schema.Type<typeof ArtifactManifest> {}

export class LoadError extends Schema.TaggedErrorClass<LoadError>()("ArtifactStore.LoadError", {
  url: Schema.String,
  reason: Schema.String,
}) {}

export interface Artifacts {
  readonly version: string;
  readonly snapshot: NetworkSnapshot;
  readonly geometry: GeometrySidecar;
}

export interface Interface extends Artifacts {}

export class Service extends Context.Service<Service, Interface>()("@transit/ArtifactStore") {}

export interface LayerOptions {
  readonly manifestUrl: string;
  readonly fetch?: typeof globalThis.fetch;
  readonly onLoad?: (url: string) => void;
}

const parseJson = (text: string): unknown => JSON.parse(text);

const decodeJson = <A>(schema: Schema.ConstraintDecoder<A>, url: string, text: string) =>
  Effect.try({
    try: () => parseJson(text),
    catch: (error) => new LoadError({ url, reason: `Invalid JSON: ${String(error)}` }),
  }).pipe(
    Effect.flatMap(Schema.decodeUnknownEffect(schema)),
    Effect.mapError((error) =>
      error instanceof LoadError
        ? error
        : new LoadError({ url, reason: `Schema validation failed: ${String(error)}` }),
    ),
  );

const responseText = async (response: Response, url: string, maximumBytes: number) => {
  const declaredLength = Number(response.headers.get("content-length") ?? "0");
  if (Number.isFinite(declaredLength) && declaredLength > maximumBytes)
    throw new LoadError({ url, reason: `Artifact exceeds ${maximumBytes} bytes` });
  if (response.body === null) throw new LoadError({ url, reason: "Artifact body is missing" });
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let bytes = 0;
  let text = "";
  while (true) {
    const next = await reader.read();
    if (next.done) break;
    bytes += next.value.byteLength;
    if (bytes > maximumBytes) {
      await reader.cancel("Artifact is too large");
      throw new LoadError({ url, reason: `Artifact exceeds ${maximumBytes} bytes` });
    }
    text += decoder.decode(next.value, { stream: true });
  }
  return text + decoder.decode();
};

const readText = Effect.fn("ArtifactStore.readText")(function* (
  fetcher: typeof globalThis.fetch,
  url: string,
  maximumBytes: number,
  onLoad?: (url: string) => void,
) {
  onLoad?.(url);
  const response = yield* Effect.tryPromise({
    try: () => fetcher(url),
    catch: (error) => new LoadError({ url, reason: `Fetch failed: ${String(error)}` }),
  });
  if (!response.ok)
    return yield* Effect.fail(
      new LoadError({ url, reason: `Artifact returned HTTP ${response.status}` }),
    );
  return yield* Effect.tryPromise({
    try: () => responseText(response, url, maximumBytes),
    catch: (error) =>
      error instanceof LoadError
        ? error
        : new LoadError({ url, reason: `Body read failed: ${String(error)}` }),
  });
});

export const load = Effect.fn("ArtifactStore.load")(function* (options: LayerOptions) {
  const fetcher = options.fetch ?? globalThis.fetch;
  const manifestText = yield* readText(fetcher, options.manifestUrl, 65_536, options.onLoad);
  const manifest = yield* decodeJson(ArtifactManifest, options.manifestUrl, manifestText);
  const snapshotUrl = new URL(manifest.snapshotUrl, options.manifestUrl).href;
  const geometryUrl = new URL(manifest.geometryUrl, options.manifestUrl).href;
  const [snapshotText, geometryText] = yield* Effect.all(
    [
      readText(fetcher, snapshotUrl, 32 * 1024 * 1024, options.onLoad),
      readText(fetcher, geometryUrl, 64 * 1024 * 1024, options.onLoad),
    ],
    { concurrency: 2 },
  );
  const snapshot = yield* decodeJson(NetworkSnapshot, snapshotUrl, snapshotText);
  const geometry = yield* decodeJson(GeometrySidecar, geometryUrl, geometryText);
  if (snapshot.generatedAt.epochMilliseconds !== geometry.generatedAt.epochMilliseconds)
    return yield* Effect.fail(
      new LoadError({
        url: options.manifestUrl,
        reason: "Topology and geometry were generated by different compilation runs",
      }),
    );
  return Service.of({ version: manifest.version, snapshot, geometry });
});

export const layer = (options: LayerOptions): Layer.Layer<Service, LoadError> =>
  Layer.effect(Service, load(options));

export const layerConfig = (
  defaultManifestUrl: string,
  fetcher: typeof globalThis.fetch = globalThis.fetch,
  onLoad?: (url: string) => void,
): Layer.Layer<Service, Config.ConfigError | LoadError> =>
  Layer.effect(
    Service,
    Config.string("TRANSIT_ARTIFACT_MANIFEST_URL").pipe(
      Config.withDefault(defaultManifestUrl),
      Effect.flatMap((manifestUrl) => load({ manifestUrl, fetch: fetcher, onLoad })),
    ),
  );

export * as ArtifactStore from "./artifact-store.js";
