/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiJourneysRouteImport } from './routes/api/journeys'
import { Route as ApiStopsRouteImport } from './routes/api/stops'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJourneysRoute = ApiJourneysRouteImport.update({
  id: '/api/journeys',
  path: '/api/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStopsRoute = ApiStopsRouteImport.update({
  id: '/api/stops',
  path: '/api/stops',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/journeys': typeof ApiJourneysRoute
  '/api/stops': typeof ApiStopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/journeys': typeof ApiJourneysRoute
  '/api/stops': typeof ApiStopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/journeys': typeof ApiJourneysRoute
  '/api/stops': typeof ApiStopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/journeys' | '/api/stops'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/journeys' | '/api/stops'
  id: '__root__' | '/' | '/api/journeys' | '/api/stops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiJourneysRoute: typeof ApiJourneysRoute
  ApiStopsRoute: typeof ApiStopsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/journeys': {
      id: '/api/journeys'
      path: '/api/journeys'
      fullPath: '/api/journeys'
      preLoaderRoute: typeof ApiJourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stops': {
      id: '/api/stops'
      path: '/api/stops'
      fullPath: '/api/stops'
      preLoaderRoute: typeof ApiStopsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiJourneysRoute: ApiJourneysRoute,
  ApiStopsRoute: ApiStopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
