/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiArtifactVersionsRouteImport } from './routes/api/artifact-versions'
import { Route as ApiJourneysRouteImport } from './routes/api/journeys'
import { Route as ApiNearbyTransitRouteImport } from './routes/api/nearby-transit'
import { Route as ApiPlacesRouteImport } from './routes/api/places'
import { Route as ApiRouteGuideRouteImport } from './routes/api/route-guide'
import { Route as ApiStopsRouteImport } from './routes/api/stops'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactVersionsRoute = ApiArtifactVersionsRouteImport.update({
  id: '/api/artifact-versions',
  path: '/api/artifact-versions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJourneysRoute = ApiJourneysRouteImport.update({
  id: '/api/journeys',
  path: '/api/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNearbyTransitRoute = ApiNearbyTransitRouteImport.update({
  id: '/api/nearby-transit',
  path: '/api/nearby-transit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesRoute = ApiPlacesRouteImport.update({
  id: '/api/places',
  path: '/api/places',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouteGuideRoute = ApiRouteGuideRouteImport.update({
  id: '/api/route-guide',
  path: '/api/route-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStopsRoute = ApiStopsRouteImport.update({
  id: '/api/stops',
  path: '/api/stops',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/artifact-versions': typeof ApiArtifactVersionsRoute
  '/api/journeys': typeof ApiJourneysRoute
  '/api/nearby-transit': typeof ApiNearbyTransitRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/route-guide': typeof ApiRouteGuideRoute
  '/api/stops': typeof ApiStopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/artifact-versions': typeof ApiArtifactVersionsRoute
  '/api/journeys': typeof ApiJourneysRoute
  '/api/nearby-transit': typeof ApiNearbyTransitRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/route-guide': typeof ApiRouteGuideRoute
  '/api/stops': typeof ApiStopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/artifact-versions': typeof ApiArtifactVersionsRoute
  '/api/journeys': typeof ApiJourneysRoute
  '/api/nearby-transit': typeof ApiNearbyTransitRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/route-guide': typeof ApiRouteGuideRoute
  '/api/stops': typeof ApiStopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/artifact-versions'
    | '/api/journeys'
    | '/api/nearby-transit'
    | '/api/places'
    | '/api/route-guide'
    | '/api/stops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/artifact-versions'
    | '/api/journeys'
    | '/api/nearby-transit'
    | '/api/places'
    | '/api/route-guide'
    | '/api/stops'
  id:
    | '__root__'
    | '/'
    | '/api/artifact-versions'
    | '/api/journeys'
    | '/api/nearby-transit'
    | '/api/places'
    | '/api/route-guide'
    | '/api/stops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiArtifactVersionsRoute: typeof ApiArtifactVersionsRoute
  ApiJourneysRoute: typeof ApiJourneysRoute
  ApiNearbyTransitRoute: typeof ApiNearbyTransitRoute
  ApiPlacesRoute: typeof ApiPlacesRoute
  ApiRouteGuideRoute: typeof ApiRouteGuideRoute
  ApiStopsRoute: typeof ApiStopsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifact-versions': {
      id: '/api/artifact-versions'
      path: '/api/artifact-versions'
      fullPath: '/api/artifact-versions'
      preLoaderRoute: typeof ApiArtifactVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/journeys': {
      id: '/api/journeys'
      path: '/api/journeys'
      fullPath: '/api/journeys'
      preLoaderRoute: typeof ApiJourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nearby-transit': {
      id: '/api/nearby-transit'
      path: '/api/nearby-transit'
      fullPath: '/api/nearby-transit'
      preLoaderRoute: typeof ApiNearbyTransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places': {
      id: '/api/places'
      path: '/api/places'
      fullPath: '/api/places'
      preLoaderRoute: typeof ApiPlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/route-guide': {
      id: '/api/route-guide'
      path: '/api/route-guide'
      fullPath: '/api/route-guide'
      preLoaderRoute: typeof ApiRouteGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stops': {
      id: '/api/stops'
      path: '/api/stops'
      fullPath: '/api/stops'
      preLoaderRoute: typeof ApiStopsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiArtifactVersionsRoute: ApiArtifactVersionsRoute,
  ApiJourneysRoute: ApiJourneysRoute,
  ApiNearbyTransitRoute: ApiNearbyTransitRoute,
  ApiPlacesRoute: ApiPlacesRoute,
  ApiRouteGuideRoute: ApiRouteGuideRoute,
  ApiStopsRoute: ApiStopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
